# -*- Mode: Makefile; indent-tabs-mode:t; tab-width: 4 -*-

all:

install:
	cp -a start-gateway.sh $(DESTDIR)/start-gateway
	cp -ra magic-bin $(DESTDIR)/
	cp -ra lib $(DESTDIR)/
	chmod a+x $(DESTDIR)/start-gateway
